In [58]:
# Update files
import importlib
import config as cfg
import utils.io

importlib.reload(cfg)
importlib.reload(utils.io)

# Import functions
from utils.io import extract_and_clean_data

In [ ]:
# If we drop all NANs we lose around 40% of the dataset (150k to 93k) still a good amount
df = extract_and_clean_data(file_path=cfg.DATA_PATH, drop_NAN=True, save=False)

Clean data save completed in folder c:\Users\Asus\Desktop\Git\master-projects\data-analysis-technologies\src\..\assets\clean_data.csv...
Raw data extraction & cleaning completed...

In [60]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Reason for cancelling by Customer,Driver Cancellation Reason,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),627.0,13.58,4.9,4.9
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),416.0,34.02,4.6,5.0
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),737.0,48.21,4.1,4.3
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),316.0,4.85,4.1,4.6
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),640.0,41.24,4.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),475.0,40.08,3.7,4.1
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),1093.0,21.31,4.8,5.0
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),852.0,15.93,3.9,4.4
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),333.0,45.54,4.1,3.7
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,Não Cancelado pelo Cliente,Não Cancelado pelo Condutor,Viagem Completa (Sem problemas),806.0,21.19,4.6,4.9

In [61]:
df.describe()

,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,93000.000000,93000.000000,93000.000000,93000.000000,93000.000000,93000.000000
mean,8.511878,30.034772,508.178215,26.000493,4.230992,4.404584
std,3.748138,8.650707,396.058769,13.824176,0.436871,0.437819
min,2.000000,15.000000,50.000000,2.000000,3.000000,3.000000
25%,5.300000,22.600000,234.000000,14.100000,4.100000,4.200000
50%,8.500000,30.000000,414.000000,26.020000,4.300000,4.500000
75%,11.800000,37.500000,689.000000,37.942500,4.600000,4.800000
max,15.000000,45.000000,4277.000000,50.000000,5.000000,5.000000